name: ${project.name}
version: '${project.version}'
main: ${project.groupId}.${project.artifactId}
author: yancie
api-version: 1.19

commands:
  ${project.name}:
    description: ${project.name}
  test:
    description: 测试

permissions:
  ${project.name}.admin:
    default: op
